# Generated by Django 4.1.5 on 2023-02-06 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tracker', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='transactions',
            name='transaction_discr',
            field=models.CharField(max_length=200, null=True),
        ),
    ]
